const fleetMoney = new Intl.NumberFormat("en-GB", { currency: "GBP", maximumFractionDigits: 0, style: "currency" });
const fleetState = { items: [], query: "" };
function fleetToast(message){const node=document.querySelector("#master-toast");node.textContent=message;node.classList.add("show");clearTimeout(fleetToast.timer);fleetToast.timer=setTimeout(()=>node.classList.remove("show"),2300);}
function totals(){return fleetState.items.reduce((sum,item)=>({orders:sum.orders+item.orders,revenue:sum.revenue+item.revenue,saved:sum.saved+item.commissionSaved,live:sum.live+(item.active?1:0)}),{orders:0,revenue:0,saved:0,live:0});}
function renderMetrics(){const total=totals();document.querySelector("#fleet-metrics").innerHTML=`<article><span>Live takeaways</span><strong>${total.live}</strong></article><article><span>Weekly orders</span><strong>${total.orders}</strong></article><article><span>Weekly sales</span><strong>${fleetMoney.format(total.revenue)}</strong></article><article><span>Fees avoided</span><strong>${fleetMoney.format(total.saved)}</strong></article>`;}
function visibleStores(){return fleetState.items.filter((item)=>`${item.name} ${item.postcode}`.toLowerCase().includes(fleetState.query.toLowerCase()));}
function renderStores(){document.querySelector("#fleet-table").innerHTML=visibleStores().map((item,index)=>`<article class="store-row ${item.active?"":"paused"}" data-store="${item.id}"><div><small>${item.postcode}</small><h3>${item.name}</h3><span>${item.active?"Live":"Paused"}</span></div><b>${item.orders} orders</b><b>${fleetMoney.format(item.revenue)}</b><em>${item.conversion}% conversion</em><div><a href="${item.id==="harbour-street-kitchen"?"../dashboard/":"#"}">${item.id==="harbour-street-kitchen"?"Control":"Pending"}</a><button data-toggle="${index}">${item.active?"Pause":"Activate"}</button></div></article>`).join("");document.querySelectorAll("[data-toggle]").forEach((button)=>button.addEventListener("click",async()=>{const item=fleetState.items[Number(button.dataset.toggle)];item.active=!item.active;fleetState.items=await ZeroFleetApi.saveFleet(fleetState.items);render();fleetToast(`${item.name} ${item.active?"activated":"paused"}.`);}));}
function renderFigures(){const total=totals();const days=[["Mon",.11],["Tue",.14],["Wed",.13],["Thu",.16],["Fri",.2],["Sat",.18],["Sun",.08]];document.querySelector("#weekly-bars").innerHTML=days.map(([day,share])=>`<article class="bar-row"><header><span>${day}</span><strong>${fleetMoney.format(total.revenue*share)}</strong></header><div class="bar-track"><i style="width:${share*360}%"></i></div></article>`).join("");document.querySelector("#watch-list").innerHTML=fleetState.items.map((item)=>`<article><div><strong>${item.name}</strong><p>${item.orders} direct orders this week</p></div><b>${fleetMoney.format(item.commissionSaved)} saved</b></article>`).join("");}
function render(){renderMetrics();renderStores();renderFigures();}
document.querySelector("#fleet-search").addEventListener("input",(event)=>{fleetState.query=event.target.value.trim();renderStores();});
document.querySelector("#new-takeaway").addEventListener("submit",async(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);const name=data.get("name").trim();fleetState.items.unshift({active:true,commissionSaved:0,conversion:0,id:ZeroFleetApi.createId(name),name,orders:0,postcode:data.get("postcode").trim().toUpperCase(),revenue:0});fleetState.items=await ZeroFleetApi.saveFleet(fleetState.items);event.currentTarget.reset();render();fleetToast(`${name} added to master operations.`);});
(async function bootMaster(){fleetState.items=await ZeroFleetApi.listFleet();render();})();
